### ISSUE TITLE
Optimize dice reducer

### ISSUE THREAD

**Issue by known-as-bmf** [mhogeveen/dnd_dice_roller#1]
Hello,

I didn't know how to add feedback to your code so I thought issues might be a good place.

https://github.com/mhogeveen/dnd_dice_roller/blob/b99796b18765fa68eaaf73e0d4b831e9938f8847/src/reducers/diceReducer.js#L10-L47

Instead of using an array that you have to iterate each time you dispatch an action (O(N) complexity, N being the number of rows)

```ts
        // when you want to update the amount of a specific dice type, you iterate over the whole list
         return state.map((die) =>
            die.id === action.id ? { ...die, dieAmount: action.payload } : die
         )
```
You could use an object, making the update O(1).

```ts
const initialState = {
   0: {
      dieAmount: 1,
      dieType: 4,
      modAmount: 0,
   },
   1: {
      dieAmount: 1,
      dieType: 6,
      modAmount: 0,
   },
   2: {
      dieAmount: 1,
      dieType: 8,
      modAmount: 0,
   },
   3: {
      dieAmount: 1,
      dieType: 10,
      modAmount: 0,
   },
   4: {
      dieAmount: 1,
      dieType: 12,
      modAmount: 0,
   },
   5: {
      dieAmount: 1,
      dieType: 20,
      modAmount: 0,
   },
}

// ...

export default (state = initialState, action) => {
  switch (action.type) {
    case UPDATE_DIE_AMOUNT:
      return {
        ...state,
        [action.id]: { ...state[action.id], dieAmount: action.payload },
      };
    case UPDATE_DIE_TYPE:
      return {
        ...state,
        [action.id]: { ...state[action.id], dieType: action.payload },
      };
    case UPDATE_MOD_AMOUNT:
      return {
        ...state,
        [action.id]: { ...state[action.id], modAmount: action.payload },
      };
    case RESET_ROW:
      return { ...state, [action.id]: { ...resetDie } };
    case REMOVE_ROW:
      const { [action.id]: _, ...newState } = state;
      return newState;
    case ADD_ROW:
      return { ...state, [nextId()]: { ...resetDie } };
    default:
      return state;
  }
};

```

and the iteration in DiceContainer could look like this

```ts
            {Object.entries(this.props.dice).map(([id, die]) => (
               <DieRow die={die} id={id} key={id} />
            ))}
```

I know this is trivial given N, but might be helpful to know this in the future :)

**Comment by mhogeveen** [comment]
Hi @known-as-bmf,

This is actually incredibly helpful. Thank you for the feedback.

I tried a couple of options regarding the set-up for the state of the dice, and wasn't able to make it work with 'id-ed' objects like you've shown here. But thanks to your example I understand what went wrong in the way I went about it at first. I'll implement your solution as soon as possible.

The only thing I don't understand (and couldn't for the life of me find the answer to) is the following line of code:

`const { [action.id]: _, ...newState } = state;`

What exactly does the underscore mean/do after `[action.id]:`?

Thanks again for your help!

**Comment by known-as-bmf** [comment]
The underscore is simply a variable name. This instruction assigns the value at index `[action.id]` to a variable named `_`.

It is convention in [some languages](https://docs.microsoft.com/en-us/dotnet/csharp/discards) to name a "discarded variable" `_`. By "discarded", I mean that we will never use it. We only destructure it to remove it from `state`.

Linters usually warn about unused variables, but naming it `_` instruct them to not yield warnings / errors "unused variable ..." for this specific variable (we are knowingly discarding it).

**Comment by mhogeveen** [comment]
Ok, so it's more of a convention than a rule. I will keep that in mind the next time I need to discard a variable.

Thanks for taking your time to answer my question!

I'll close this issue for now.
